# Generated by Django 3.2.5 on 2021-09-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PageHeadingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('summary_text', models.CharField(max_length=2000)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='corwin.pagename')),
            ],
        ),
        migrations.CreateModel(
            name='PageBodyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('summary_text', models.CharField(max_length=2000)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='corwin.pagename')),
            ],
        ),
    ]
