# Generated by Django 3.2.7 on 2021-09-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corwin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='pageheadingtopic',
            name='summary_text',
            field=models.TextField(max_length=2000),
        ),
        migrations.DeleteModel(
            name='PageBodyTopic',
        ),
    ]
