# Generated by Django 3.2.7 on 2021-09-12 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corwin', '0002_auto_20210912_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageheadingtopic',
            name='topic_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='corwin.topictype'),
        ),
    ]
