# Generated by Django 3.2.7 on 2021-11-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corwin', '0003_pageheadingtopic_topic_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('summary_text', models.TextField(max_length=2000)),
                ('page_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Page Topics',
            },
        ),
        migrations.AlterModelOptions(
            name='pagename',
            options={'verbose_name_plural': 'Page Names'},
        ),
        migrations.AlterModelOptions(
            name='topictype',
            options={'verbose_name_plural': 'Topic Types'},
        ),
        migrations.DeleteModel(
            name='PageHeadingTopic',
        ),
        migrations.AddField(
            model_name='pagetopic',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='corwin.pagename'),
        ),
        migrations.AddField(
            model_name='pagetopic',
            name='topic_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='corwin.topictype'),
        ),
    ]
